name: shro2026_environment
channels:
  - conda-forge
dependencies:
  - jupyter 
  - matplotlib >= 3.8
  - pandas >= 2.0
  - pip >= 24.0
  - spyder
  - spyder-notebook
  - python = 3.12
  - scikit-learn >= 1.4
  - scipy
  - numpy
  - yfinance
  - pydmd
